"""initial_schema

Revision ID: 34234dc587a8
Revises: 
Create Date: 2026-05-11 11:39:59.794798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34234dc587a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('driver_id', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('circuit_name', sa.String(length=100), nullable=False),
    sa.Column('circuit_key', sa.String(length=50), nullable=True),
    sa.Column('session_type', sa.String(length=10), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('laps',
    sa.Column('lap_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=10), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time', sa.Float(), nullable=True),
    sa.Column('sector1_time', sa.Float(), nullable=True),
    sa.Column('sector2_time', sa.Float(), nullable=True),
    sa.Column('sector3_time', sa.Float(), nullable=True),
    sa.Column('compound', sa.String(length=20), nullable=True),
    sa.Column('tyre_age', sa.Integer(), nullable=True),
    sa.Column('stint_number', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('pit_in_time', sa.Float(), nullable=True),
    sa.Column('pit_out_time', sa.Float(), nullable=True),
    sa.Column('track_status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('lap_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=10), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('shap_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('weather',
    sa.Column('weather_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('air_temp', sa.Float(), nullable=True),
    sa.Column('track_temp', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_dir', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_table('telemetry',
    sa.Column('telemetry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lap_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('throttle', sa.Float(), nullable=True),
    sa.Column('brake', sa.Float(), nullable=True),
    sa.Column('gear', sa.Integer(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('drs', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.lap_id'], ),
    sa.PrimaryKeyConstraint('telemetry_id')
    )
    op.create_index('ix_telemetry_lap_timestamp', 'telemetry', ['lap_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_lap_timestamp', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_table('weather')
    op.drop_table('predictions')
    op.drop_table('laps')
    op.drop_table('sessions')
    op.drop_table('drivers')
    # ### end Alembic commands ###
